### ISSUE TITLE
Standardize the Code

### ISSUE THREAD

**Issue by ashlynn-cleveland** [DevCoder0x0/uncommonschools#24]
I think we've made a lot of progress, and the overall web page looks pretty great. I noticed that our heading sizes and section paddings were diverging a little bit. Is it alright if I go in and make it look more consistent? Would it also be alright to rearrange the CSS, so the different sections will be in order?

**Comment by ashlynn-cleveland** [comment]
I created a branch called "fixes" locally. It made all h2 headers 32px and gave all sections(with exclusion of the footer) a padding or margin of 48px(top and bottom only). I won't merge or create a pull request unless you guys are okay with it though.

**Comment by AlainPicard0x0** [comment]
I agree. I noticed the font sizes and container sizes were different and we definitely should have everything consistent.

**Comment by ashlynn-cleveland** [comment]
Ok, great :)
